### ISSUE TITLE
assetで画像とフォント扱えるようになる

### ISSUE THREAD

**Issue by cycling777** [cycling777/flutterUITest#1]
### 画像とフォントを扱えるようになりたい

pubspec.yaml
```
flutter:
  uses-material-design: true
  assets:
    - assets/images/waiting.png
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
```
こんな感じ
